kubectl:
  # update to the latest supported k8s releases
  # ref: https://kubernetes.io/releases
  versions:
    - v1.26.1
    - v1.25.6
    - v1.24.10
    - v1.23.16

# update to the latest version of helm
# ref: https://github.com/helm/helm/releases
helm:
  version: v3.11.1

# update to the latest version of kustomize
# ref: https://github.com/kubernetes-sigs/kustomize/releases
kustomize:
  version: v5.0.0

# update to the latest version of kubeconform
# ref: https://github.com/yannh/kubeconform/releases
kubeconform:
  version: v0.6.1
